import pandas as pd
archivo = pd.read_csv("bases_datos/REGISTROS_ACTIVOS_DECADA_2012_A_2022_PEQUE_A_Y_MEDIANA_EMPRESA_JURISDICCION_CAMARA_COMERCIO_VILLAVICENCIO.csv")
print(archivo["RAZON SOCIAL"].head())
"""
['MATRICULA', 'ORGANIZACION', 'EST-MATRICULA', 'RAZON SOCIAL',
       'FEC-MATRICULA', 'FEC-RENOVACION', 'ULT-ANO_REN', 'DIR-COMERCIAL',
       'BARRIO-COMERCIAL', 'MUN-COMERCIAL', 'TEL-COM-1', 'EMAIL-COMERCIAL',
       'DIR-NOTIFICACION', 'MUN-NOTIFICACION', 'TEL-NOTF-1',
       'EMAIL-NOTIFICACION', 'CIIU', 'CIIU-TAM-EMPRESARIAL',
       'ING-TAM-EMPRESARIAL', 'ANO-DATOS-TAM-EMPRESARIAL', 'TAM-EMPRESA',
       'PERSONAL', 'ACTIVO-TOTAL', 'ING-OPERACIONES']
"""